EXPLORER_WIN = 0
REFERENCE_WIN = 1
SETTINGS_WIN = 2

LIGHT_THEME = 0
DARK_THEME = 1

SAVENEEDED_FALSE = -1
SAVENEEDED_CLOSE_NOSAVE = 0
SAVENEEDED_CLOSE_SAVE = 1
SAVENEEDED_CLOSE_CANCEL = 2

CONFIRMDELETE_DELETE = 3
CONFIRMDELETE_CANCEL = 4

CONFIRMMOVE_MOVE = 5
CONFIRMMOVE_CANCEL = 6

POPUP_SAVENEEDED = 0
POPUP_CONFIRMMOVE = 1
POPUP_CONFIRMDELETE = 2